services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_NAME: EvidencijaRecepata
      APP_ENV: production
      APP_KEY: base64:HQDznLHuJdwM1ZwICNp+mnOCxF0IN5gVWE5zKLOJKTs=
      APP_DEBUG: "false"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: evidencija_recepata
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      SESSION_DRIVER: database
      CACHE_STORE: database
      L5_SWAGGER_GENERATE_ALWAYS: "true"
      L5_SWAGGER_CONST_HOST: http://localhost:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: evidencija_recepata
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ularavel", "-psecret"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: